export const governanceInputGuidance = Object.freeze([
  "verify forbids attestation; create, amend, retire, and delete require it. Presence and JSON shape do not authenticate a Maintainer. Obtain approval for the exact request separately; do not copy example identities as approval.",
  "For a new top-level .atlas/principles/<slug>.md page, sdk.id must be principle:<slug>; .atlas/principles/quality.md uses principle:quality. New .atlas/types/policy/<slug>.md pages use policy:<slug>. An existing page must retain its captured identity. These path-derived rules do not define nested-directory identity conventions.",
  "changes[].content is the complete Markdown page, including sdk and atlas YAML frontmatter. Match sdk.title to the H1, retain existing creation metadata and the immutable established-by DRI, and use real authorship and timestamp values. The example is a template, not a record of a human decision.",
  "An active Principle uses the exact column-1 heading ## Active truths and column-1 bullets shaped as - `stable-truth-id` Non-empty truth text. Truth IDs must be unique within that Principle; they are not page IDs and need no page-type prefix. Every live Principle has at least one active truth.",
  "Governance Retirement purges the live Principle or Atlas Policy rather than keeping an empty page or tombstone. Use retire or delete with null change content and a changelog reason. The operation records what, when, who and why, preserves the document in Git history, and refuses invalid remaining dependencies.",
  "Preserve the ## Amendments history. Append a numbered, dated entry recording added, changed, or invalidated truths, the directing or approving Maintainer, rationale, and change reference. A new amendment does not replace the original established-by DRI. Meaning-preserving clarification retains a truth ID; semantic replacement invalidates the old truth and records a linked successor with a new ID.",
  "changelog is optional single-line prose, not the full .atlas/CHANGELOG.md file. Do not put that derived file in changes: Atlas SDK stamps its entry. Approval and semantic Policy verdicts remain caller-supplied; disagreement with a Challenge escalates rather than becoming approval.",
]);

export const governancePrincipleExample = Object.freeze({
  notice:
    "Illustrative template, not approval. Replace example identities, dates, truths, rationale, and change references with the actual human-directed record before submission.",
  path: ".atlas/principles/quality.md",
  content: [
    "---",
    "sdk:",
    "  atlas-sdk-schema: 1.0.0",
    '  created-at: "2026-08-22T00:00:00Z"',
    "  created-by:",
    "    kind: human",
    "    name: Example Maintainer",
    "  id: principle:quality",
    "  local-atlas-schema: 1.0.0",
    "  tags: []",
    "  title: Quality",
    "  type: principle",
    '  updated-at: "2026-08-22T00:00:00Z"',
    "  updated-by:",
    "    kind: human",
    "    name: Example Maintainer",
    "atlas: {}",
    "---",
    "",
    "# Quality",
    "",
    "## Scope",
    "",
    "This Principle governs deterministic knowledge validation.",
    "",
    "## Active truths",
    "",
    "- `quality-v1` Trusted validation is deterministic.",
    "",
    "## Amendments",
    "",
    "### 1 - 2026-08-22",
    "",
    "Added `quality-v1`.",
    "Maintainer: Example Maintainer (illustrative, not an approval record).",
    "Rationale: Keep validation reproducible.",
    "Change reference: Replace with the actual reviewed change reference.",
    "",
  ].join("\n"),
  replacementAmendment: [
    "### 2 - 2026-08-23",
    "",
    "Invalidated `quality-v1`.",
    "Added `quality-v2` as its linked successor; move the new truth into Active truths and remove the old active bullet.",
    "Maintainer: Replace with the actual directing or approving human.",
    "Rationale: Record why the old meaning was replaced.",
    "Change reference: Replace with the actual reviewed change reference.",
    "",
  ].join("\n"),
});
